# group_vars/all.yml

# master
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
control_plane: 192.168.8.4
lb_ip_pool:
  - 192.168.10.0/24

# k3s
K3S_CONFIG_FILE: /etc/rancher/k3s/k3s.yaml
INSTALL_K3S_VERSION: v1.30.1+k3s1

# Cilium
CLUSTER_CIDR: 10.42.0.0/16
CILIUM_NAMESPACE: kube-system
CILIUM_VERSION: "1.15.5"