# group_vars/all.yml

# master
ansible_user: root # change
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
control_plane_name: wagyu.rei.lan
control_plane: 192.168.1.4
lb_ip_pool:
  - 192.168.1.90/32


# k3s
K3S_CONFIG_FILE: /etc/rancher/k3s/k3s.yaml
INSTALL_K3S_VERSION: v1.33.4+k3s1

# Cilium
CLUSTER_CIDR: 10.42.0.0/16
CILIUM_NAMESPACE: kube-system
CILIUM_VERSION: "v1.18.1"