# group_vars/all.yml

# master
ansible_user: root # change
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
control_plane: 172.16.1.4
node_virtual_ip: 10.8.0.1
node_virtual_cidr: 10.8.0.1/24
lb_ip_pool:
  - 172.16.1.5/32


# k3s
K3S_CONFIG_FILE: /etc/rancher/k3s/k3s.yaml
INSTALL_K3S_VERSION: v1.33.1+k3s1

# Cilium
CLUSTER_CIDR: 10.42.0.0/16
CILIUM_NAMESPACE: kube-system
CILIUM_VERSION: "v1.17.4"